# Generated by Django 4.2.7 on 2024-03-09 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'City must contain only letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Country must contain only letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'State must contain only letters and spaces.')]),
        ),
    ]
